export type usersGithubType =  {
        "login": string,
        "avatar_url": string,
        "html_url": string,
        "name": string,
        "company": string,
        "blog": string,
        "location": string,
        "bio": string,
        "twitter_username": string,
        "public_repos": number,
        "public_gists": number,
        "followers": number,
        "following": number,
    }
